version: '3.6'
networks:
  network:
services:

  'dnsmasq':
    restart: on-failure
    image: andyshinn/dnsmasq
    container_name: dnsmasq
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    volumes:
      - ./docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./docker/dnsmasq/hosts:/etc/hosts:ro
      - ./docker/dnsmasq/resolv.conf:/etc/resolv.conf:ro
    cap_add:
      - NET_ADMIN

  'haproxy':
    container_name: haproxy
    restart: on-failure
    image: haproxy:alpine
    networks:
      - network
    depends_on:
      - app
      - browser-sync
      - mongo
      - mongo-express
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/haproxy:/usr/local/etc/haproxy:ro

  'mongo':
    container_name: mongo
    restart: on-failure
    image: mongo:latest
    environment:
      - 'MONGODB_USER=user'
      - 'MONGODB_PASS=pass'
    networks:
      - network
    command: mongod --smallfiles
    volumes:
      - ./docker/mongo/db:/data/db

  'mongo-express':
    container_name: mongo-express
    restart: on-failure
    image: mongo-express
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=pass'
    networks:
      - network
    depends_on:
      - mongo

  'browser-sync':
    container_name: browser-sync
    restart: on-failure
    image: ustwo/browser-sync
    networks:
      - network
    depends_on:
      - app
    volumes:
      - ./docker/browser-sync/bs-config.js:/var/browser-sync/bs-config.js:ro
      - ./dst:/var/browser-sync/dst:ro
    working_dir: /var/browser-sync
    command: start --config bs-config.js

#  'webpack': # generates `./node_modules`, watches and builds files
#    container_name: webpack
#    restart: on-failure
#    build: ./docker/webpack
#    volumes:
#      - ./dst:/var/webpack/dst

  'app':
    container_name: app
    restart: on-failure
    image: keymetrics/pm2:latest-alpine
    networks:
      - network
    depends_on:
      - mongo
    extra_hosts:
      - 'langue.link:172.17.0.1'
    volumes:
      - ./dst:/var/app/dst:ro
      - ./node_modules:/var/app/node_modules:ro
      - ./.secret:/var/app/.secret:ro
      - ./docker/app/ecosystem.config.js:/var/app/ecosystem.config.js:ro
    working_dir: /var/app
    command: pm2-runtime start ecosystem.config.js --only development